In [1]:
import numpy as np

In [8]:
Prior = np.array([0.4,0.3,0.2,0.1])
lambda_ = np.array([1,2,3,4]) # El mundo de los modelos

In [9]:
Poisson = lambda mu,x : np.exp(-mu)*mu**x / np.math.factorial(x)

In [10]:
Likelihood = Poisson(lambda_,4)

In [11]:
Likelihood

array([0.01532831, 0.09022352, 0.16803136, 0.19536681])

In [12]:
Probx = np.sum(Likelihood*Prior)
Probx

0.0863413332964712

In [13]:
Posterior = (Likelihood*prior)/Probx

In [14]:
Posterior

array([0.07101262, 0.31348898, 0.38922576, 0.22627264])

In [15]:
# Caso de dos canales
JointLikelihood = Poisson(lambda_,4)*Poisson(lambda_,5)
JointLikelihood

array([4.69914178e-05, 3.25611358e-03, 1.69407219e-02, 3.05345539e-02])

In [17]:
Probx = np.sum(JointLikelihood*Prior)
Probx

0.007437230409082155

In [18]:
Posterior = (JointLikelihood*prior)/Probx

In [19]:
Posterior

array([0.00252736, 0.1313438 , 0.45556534, 0.41056351])