In [4]:
import numpy as np

In [5]:
A = np.array([[1,2,-1],[1,0,1],[4,-4,5]])
A

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 4, -4,  5]])

In [7]:
np.linalg.eig(A)

(array([3., 2., 1.]),
 array([[-0.23570226,  0.43643578,  0.40824829],
        [ 0.23570226, -0.21821789, -0.40824829],
        [ 0.94280904, -0.87287156, -0.81649658]]))

In [8]:
def EigValue(A,c=0,itmax=1000,tolerancia=1e-14):
    
    n = A.shape[0]
    
    v0 = np.zeros(n)
    
    v0[c] = 1.
    
    lambda1 = 0.
    
    for k in range(itmax):
        
        v1 = np.dot(A,v0)
        v1 = v1/np.linalg.norm(v1) # Normaliza
        
        v2 = np.dot(A,v1)
        v2 = v2/np.linalg.norm(v2)
        
        lambda0 = lambda1
        lambda1 = v2[0]/v1[0]
        
        v0 = v2
        
        if np.abs(lambda0 - lambda1) <= tolerancia:
            break
            
    return lambda1,v1

In [9]:
value1,vector1 = EigValue(A)
print(value1,vector1)

1.000000000000004 [-0.23570226  0.23570226  0.94280904]
