In [1]:
import numpy as np

In [12]:
A = np.array([[1,2,-1],[1,0,1],[4,-4,5]])
A

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 4, -4,  5]])

In [13]:
np.linalg.eig(A)

(array([3., 2., 1.]),
 array([[-0.23570226,  0.43643578,  0.40824829],
        [ 0.23570226, -0.21821789, -0.40824829],
        [ 0.94280904, -0.87287156, -0.81649658]]))

In [14]:
def EigValue(A,c=0,itmax=1000,tolerancia=1e-10):
    
    n = A.shape[0]
    
    v0 = np.zeros(n)
    
    v0[c] = 1.
    
    lambda1 = 0.
    
    for k in range(itmax):
        
        v1 = np.dot(A,v0)
        v1 = v1/np.linalg.norm(v1) # Normaliza
        
        v2 = np.dot(A,v1)
        v2 = v2/np.linalg.norm(v1)
        
        lambda0 = lambda1
        lambda1 = v2[0]/v1[0]
        
        
        v0 = v2
        
        if np.abs(lambda0 - lambda1) <= tolerancia:
            print(k)
            break
            
    return lambda1,v1

In [15]:
value1,vector1 = EigValue(A)
print(value1,vector1)

30
3.000000000036263 [-0.23570226  0.23570226  0.94280904]


$$ B = A - \lambda_{1}\vec{v}_{1}\otimes\vec{v}_{1} $$

In [18]:
def Tensor(v):
    
    n = v.shape[0]
    T = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            T[i,j] = v[i]*v[j]
    
    return T

In [19]:
v1 = np.array([1,0])
Tensor(v1)

array([[1., 0.],
       [0., 0.]])