In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,-1],[1,0,1],[4,-4,5]])
A

array([[ 1,  2, -1],
       [ 1,  0,  1],
       [ 4, -4,  5]])

In [3]:
np.linalg.eig(A)

(array([3., 2., 1.]),
 array([[-0.23570226,  0.43643578,  0.40824829],
        [ 0.23570226, -0.21821789, -0.40824829],
        [ 0.94280904, -0.87287156, -0.81649658]]))

In [4]:
def EigValue(A,c=0,itmax=1000,tolerancia=1e-10):
    
    n = A.shape[0]
    
    v0 = np.zeros(n)
    
    v0[c] = 1.
    
    lambda1 = 0.
    
    for k in range(itmax):
        
        v1 = np.dot(A,v0)
        v1 = v1/np.linalg.norm(v1) # Normaliza
        
        v2 = np.dot(A,v1)
        v2 = v2/np.linalg.norm(v1)
        
        lambda0 = lambda1
        lambda1 = v2[0]/v1[0]
        
        
        v0 = v2
        
        if np.abs(lambda0 - lambda1) <= tolerancia:
            #print(k)
            break
            
    return lambda1,v1

$$ B = A - \lambda_{1}\vec{v}_{1}\otimes\vec{v}_{1} $$

In [5]:
def Tensor(v):
    
    n = v.shape[0]
    T = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            T[i,j] = v[i]*v[j]
    
    return T

In [6]:
value1,vector1 = EigValue(A)
print(value1,vector1)

3.000000000036263 [-0.23570226  0.23570226  0.94280904]


In [7]:
Tensor1 = Tensor(vector1)

In [8]:
A1 = A.copy()

In [9]:
B = A1 - value1*Tensor1

In [10]:
value2, vector2 = EigValue(B)
print(value2,vector2)

1.9999999999712914 [0.17069719 0.23897606 0.95590424]


In [11]:
Tensor2 = Tensor(vector2)

In [12]:
C = B - value2*Tensor2
C

array([[ 0.77505828,  2.08508159, -0.65967366],
       [ 1.08508159, -0.28088578, -0.12354312],
       [ 4.34032634, -5.12354312,  0.50582751]])

In [13]:
value3, vector3 = EigValue(C)
value3

-7.553478435325765e-12