In [252]:
import numpy as np

In [293]:
A = np.array([[1.,2.,-1.],[1.,0.,1.],[4.,-4.,5.]])
A

array([[ 1.,  2., -1.],
       [ 1.,  0.,  1.],
       [ 4., -4.,  5.]])

In [294]:
np.linalg.eig(A)

(array([3., 2., 1.]),
 array([[-0.23570226,  0.43643578,  0.40824829],
        [ 0.23570226, -0.21821789, -0.40824829],
        [ 0.94280904, -0.87287156, -0.81649658]]))

In [298]:
def EigValue(A,c=0,itmax=1000,tolerancia=1e-18):
    
    n = A.shape[0]
    v0 = np.zeros(n)
    
    v0[c] = 1.        # Esta componente la asignamos a 1 al iniciar
    lambda0 = np.inf  # Valor propio indefinido al iniciar
    
    for k in range(itmax):
        
        v1 = np.dot(A,v0)
        lambda1 = v1[c]/v0[c]
        
        v1 = v1/np.linalg.norm(v1) # Normalizamos el vector luego de calcular
                    
        if np.abs(lambda0 - lambda1) <= tolerancia:
            break
           
        # Actualizamos
        lambda0 = lambda1
        #print(lambda0,v0,v1)
        v0 = v1
                 
    return lambda0,v0

In [299]:
EigValue(A)

(3.0000000000000018, array([-0.23570226,  0.23570226,  0.94280904]))

# Deflación
$$ \mathbb{B} = \mathbb{A} - \lambda_{1}(\vec{v}_{1}\otimes\vec{v}_{1}) $$

In [300]:
def Tensor(v):
    
    n = v.shape[0]
    T = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            T[i,j] = v[i]*v[j]
    
    return T

In [301]:
value1,vector1 = EigValue(A)
print(value1,vector1)

3.0000000000000018 [-0.23570226  0.23570226  0.94280904]


In [304]:
# Lo hacemos para todos valores propios
def GetEigValues(A):
    
    A1 = A.copy()
    
    values = np.zeros(A1.shape[0])
    vectors = np.zeros_like(A1)
    
    for i in range(A.shape[0]):
        
        l,v = EigValue(A1,i) 
        
        values[i] = l
        vectors[:,i] = v
      
        # Deflación: los vectores propios de B no necesariamente son los de A
        B = A1 - l*Tensor(v)
        
        # Actualizamos la matriz
        A1 = B
        
    return values,vectors

In [305]:
GetEigValues(A)

(array([3., 2., 1.]),
 array([[-0.23570226,  0.17069719, -0.46316957],
        [ 0.23570226,  0.23897606, -0.31237017],
        [ 0.94280904,  0.95590424, -0.82939667]]))

In [306]:
np.linalg.eig(A)

(array([3., 2., 1.]),
 array([[-0.23570226,  0.43643578,  0.40824829],
        [ 0.23570226, -0.21821789, -0.40824829],
        [ 0.94280904, -0.87287156, -0.81649658]]))

In [312]:
# Otro ejemplo
B = np.array([[-4.,-5.],[1.,2.]])
GetEigValues(B)

(array([-3.,  1.]),
 array([[-0.98058068, -0.93499753],
        [ 0.19611614,  0.35465423]]))

In [316]:
values2, vectors2 = np.linalg.eig(B)
print(values2,vectors2)

[-3.  1.] [[-0.98058068  0.70710678]
 [ 0.19611614 -0.70710678]]


In [317]:
# Veamos que el segundo vetor propio es catacteristico de C
C = B - values2[0]*Tensor(vectors2[:,0])
C

array([[-1.11538462, -5.57692308],
       [ 0.42307692,  2.11538462]])

In [318]:
np.linalg.eig(C)

(array([-1.77635684e-15,  1.00000000e+00]),
 array([[-0.98058068,  0.93499753],
        [ 0.19611614, -0.35465423]]))