In [25]:
import numpy as np

In [26]:
A = np.array([[1.,2.,-1.],[1.,0.,1.],[4.,-4.,5.]])
A

array([[ 1.,  2., -1.],
       [ 1.,  0.,  1.],
       [ 4., -4.,  5.]])

In [27]:
np.linalg.eig(A)

(array([3., 2., 1.]),
 array([[-0.23570226,  0.43643578,  0.40824829],
        [ 0.23570226, -0.21821789, -0.40824829],
        [ 0.94280904, -0.87287156, -0.81649658]]))

In [46]:
def EigValue(A,c=0,itmax=100,tolerancia=1e-15):
    
    n = A.shape[0]
    
    v0 = np.zeros(n)
    
    v0[c] = 1.
    
    lambda1 = 0.
    
    for k in range(itmax):
        
        v1 = np.dot(A,v0)
        v1 = v1/np.linalg.norm(v1) # Normaliza
        
        v2 = np.dot(A,v1)
        #v2 = v2/np.linalg.norm(v1)
        
        lambda0 = lambda1
        lambda1 = v2[0]/v1[0]
        
        v0 = v2
        
        if np.abs(lambda0 - lambda1) <= tolerancia:
            #print(k)
            break
            
    return lambda1,v1

# Deflación
$$ \mathbb{B} = \mathbb{A} - \lambda_{1}(\vec{v}_{1}\otimes\vec{v}_{1}) $$

In [47]:
def Tensor(v):
    
    n = v.shape[0]
    T = np.zeros((n,n))
    
    for i in range(n):
        for j in range(n):
            T[i,j] = v[i]*v[j]
    
    return T

In [48]:
value1,vector1 = EigValue(A)
print(value1,vector1)

3.000000000000001 [-0.23570226  0.23570226  0.94280904]


In [49]:
def GetEigValues(A):
    
    A1 = A.copy()
    
    values = np.zeros(A.shape[0])
    vectors = np.zeros_like(A)
    
    for i in range(A.shape[0]):
        
        l,v = EigValue(A1,i)
        
        values[i] = l
        vectors[:,i] = v
      
        # Deflación, los vectores propios de B no son los de A
        B = A1 - l*Tensor(v)
        
        # Actualizamos la matriz
        A1 = B
        
    return values,vectors

In [50]:
GetEigValues(A)

(array([3., 2., 1.]),
 array([[-0.23570226,  0.17069719, -0.46316957],
        [ 0.23570226,  0.23897606, -0.31237017],
        [ 0.94280904,  0.95590424, -0.82939667]]))

In [51]:
np.linalg.eig(A)

(array([3., 2., 1.]),
 array([[-0.23570226,  0.43643578,  0.40824829],
        [ 0.23570226, -0.21821789, -0.40824829],
        [ 0.94280904, -0.87287156, -0.81649658]]))