In [3]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import cm
from mpl_toolkits.mplot3d import axes3d

In [4]:
sigm = lambda x: 1/(1+np.exp(-x))

In [27]:
class Layer:
    
    def __init__(self, NC, NN, ActFunc):
        
        self.NC = NC
        self.NN = NN
        self.ActFunc = ActFunc
        
        self.W = np.random.uniform( -10,10, size=(self.NC,self.NN) )
        self.b = np.random.uniform( -10,10, size=(1,self.NN) )
        
    def Activation(self,x):
        z = np.dot(x,self.W) + self.b
        return self.ActFunc(z)[0]
    
    def Mutate(self):
        self.W += np.random.normal( loc=0.,scale=0.05,size=(self.NC,self.NN) )
        self.b += np.random.normal( loc=0.,scale=0.05,size=(1,self.NN) )
        

In [28]:
L0 = Layer(2,4,sigm)

In [29]:
L0.W

array([[-6.1786611 ,  6.43114532, -5.78382414,  0.14439184],
       [ 0.30431398, -3.38988695, -3.44003589, -9.25747639]])

In [30]:
L0.b

array([[-8.23759498, -8.56583437, -2.81471976, -3.81981355]])

In [31]:
x = [0.1,0.5]

In [32]:
L0.Activation(x)

array([1.66008739e-04, 6.65384984e-05, 5.98128789e-03, 2.17278664e-04])

In [33]:
L0.Mutate()

In [34]:
L0.Activation(x)

array([1.68849589e-04, 6.45193509e-05, 5.42993372e-03, 1.98947082e-04])